nelmio_api_doc:
    documentation:
        info:
            title: sf_resto_API
            description: API du Quai Antique made by caim!
            version: 1.0.0
        components:
          securitySchemes:
            Bearer:
              type: http
              scheme: bearer
              bearerFormat: JWT
              description: "Utiliser un token d'un utilisateur avec ROLE_USER"
            AdminBearer:
              type: http
              scheme: bearer
              bearerFormat: JWT
              description: "Utiliser un token d'un utilisateur avec ROLE_ADMIN"
    areas: # to filter documented areas
      default:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
